-- INSERTS GENRES

INSERT INTO GENRE(ID, NAME) VALUES (1,'BLUES');

INSERT INTO GENRE(ID, NAME) VALUES (2,'ROCK');

INSERT INTO GENRE(ID, NAME) VALUES (3,'HEAVY');

INSERT INTO GENRE(ID, NAME) VALUES (4,'FOLK');

INSERT INTO GENRE(ID, NAME) VALUES (5,'JAZZ');

COMMIT;